# Generated by Django 5.2.16 on 2026-07-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_department_alter_user_is_employee_alter_user_is_hr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
