# Generated by Django 5.2.16 on 2026-07-22 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='casual_leave_balance',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='personal_leave_balance',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='sick_leave_balance',
            field=models.IntegerField(default=15),
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('SL', 'Sick Leave'), ('PL', 'Personal Leave'), ('CL', 'Casual Leave')], default='CL', max_length=2)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
